datasource:
  driver-class-name: org.postgresql.Driver
  username: polsky
  password: polsky
  url: jdbc:postgresql://localhost:5434/coworking_service_db
liquibase:
  enabled: true
  change-log: db.changelog/changelog.xml
  liquibase-schema: migration
jwt:
  secret: 5dd9ade89e9be4706575d59783c87cac447dc7ac525661c83252848ce5d70f92
  lifetime: PT20M